def get_char(row, col):
    if row == 0:
        return ' '

    elif row == 1:
        return ' '

    elif row == 2:
        return ' '

    elif row == 3:
        return ' '

    elif row == 4:
        return ' '

    elif row == 5:
        return ' '

    elif row == 6:
        if 50 <= col <= 52: return '.'
        return ' '

    elif row == 7:
        if 39 <= col <= 41: return '.'
        if 42 <= col <= 58: return ':'
        if 59 <= col <= 62: return '.'
        return ' '

    elif row == 8:
        if 34 <= col <= 35: return '.'
        if 36 <= col <= 48: return ':'
        if 49 <= col <= 50: return '-'
        if 51 <= col <= 65: return ':'
        if 66 <= col <= 67: return '.'
        return ' '

    elif row == 9:
        if col == 31: return '.'
        if 32 <= col <= 43: return ':'
        if 44 <= col <= 46: return '.'
        if col == 49: return '.'
        if col == 50: return ':'
        if 51 <= col <= 52: return '-'
        if 53 <= col <= 54: return ':'
        if 55 <= col <= 56: return '.'
        if 57 <= col <= 69: return ':'
        if 70 <= col <= 71: return '.'
        return ' '

    elif row == 10:
        if col == 28: return '.'
        if 29 <= col <= 35: return ':'
        if 36 <= col <= 37: return '.'
        if 38 <= col <= 39: return ':'
        if col == 40: return '-'
        if col == 41: return ':'
        if 52 <= col <= 53: return '-'
        if 54 <= col <= 55: return ':'
        if col == 56: return '-'
        if 57 <= col <= 58: return ':'
        if 59 <= col <= 62: return '.'
        if 63 <= col <= 65: return ':'
        if 66 <= col <= 67: return '.'
        if 68 <= col <= 73: return ':'
        if col == 74: return '.'
        return ' '

    elif row == 11:
        if 26 <= col <= 38: return ':'
        if col == 39: return '-'
        if col == 40: return '.'
        if col == 52: return '.'
        if col == 53: return '='
        if col == 54: return '-'
        if col == 55: return ':'
        if col == 56: return '.'
        if col == 65: return ':'
        if col == 66: return '-'
        if 67 <= col <= 73: return ':'
        if col == 74: return '-'
        if col == 75: return ':'
        if col == 76: return '.'
        return ' '

    elif row == 12:
        if col == 24: return ':'
        if col == 25: return '-'
        if 26 <= col <= 36: return ':'
        if 37 <= col <= 38: return '-'
        if col == 39: return '.'
        if 48 <= col <= 49: return '.'
        if col == 52: return '.'
        if col == 53: return '='
        if col == 54: return '.'
        if col == 66: return ':'
        if col == 67: return '-'
        if 68 <= col <= 74: return ':'
        if 75 <= col <= 77: return '-'
        if col == 78: return ':'
        return ' '

    elif row == 13:
        if col == 22: return '.'
        if 23 <= col <= 24: return '-'
        if 25 <= col <= 29: return ':'
        if 30 <= col <= 37: return '-'
        if col == 38: return ':'
        if col == 46: return ':'
        if 47 <= col <= 49: return '+'
        if col == 52: return ':'
        if col == 53: return '.'
        if col == 56: return '.'
        if col == 66: return '.'
        if col == 67: return '='
        if 68 <= col <= 77: return ':'
        if 78 <= col <= 79: return '-'
        if col == 80: return ':'
        return ' '

    elif row == 14:
        if col == 21: return ':'
        if col == 22: return '-'
        if 23 <= col <= 25: return ':'
        if 26 <= col <= 29: return '-'
        if 30 <= col <= 31: return ':'
        if 32 <= col <= 33: return '.'
        if col == 37: return ':'
        if col == 38: return '.'
        if col == 45: return '.'
        if 46 <= col <= 47: return '+'
        if col == 48: return ':'
        if col == 49: return '='
        if col == 51: return '.'
        if col == 52: return '-'
        if col == 54: return '.'
        if col == 55: return '='
        if col == 56: return '*'
        if col == 57: return '+'
        if col == 58: return ':'
        if col == 67: return '='
        if col == 68: return '-'
        if 69 <= col <= 75: return ':'
        if col == 76: return '-'
        if col == 77: return ':'
        if 78 <= col <= 79: return '-'
        if col == 80: return '='
        if col == 81: return '-'
        if col == 82: return '.'
        return ' '

    elif row == 15:
        if col == 19: return '.'
        if 20 <= col <= 21: return '-'
        if col == 22: return ':'
        if 23 <= col <= 26: return '-'
        if col == 27: return ':'
        if col == 28: return '.'
        if col == 37: return ':'
        if col == 38: return '.'
        if col == 45: return '.'
        if col == 46: return '+'
        if col == 47: return '*'
        if col == 48: return '='
        if col == 49: return ':'
        if col == 50: return '.'
        if col == 51: return '='
        if col == 52: return '.'
        if col == 54: return '-'
        if col == 55: return '*'
        if col == 56: return '-'
        if col == 57: return '*'
        if col == 58: return '='
        if col == 67: return '='
        if 68 <= col <= 69: return '-'
        if col == 70: return ':'
        if 71 <= col <= 81: return '-'
        if col == 82: return '='
        if col == 83: return ':'
        return ' '

    elif row == 16:
        if 16 <= col <= 17: return '.'
        if col == 18: return ':'
        if col == 19: return '='
        if 20 <= col <= 22: return '-'
        if col == 23: return '='
        if col == 24: return ':'
        if col == 25: return '.'
        if col == 28: return '.'
        if col == 29: return ':'
        if 30 <= col <= 31: return '.'
        if col == 38: return ':'
        if col == 39: return '.'
        if col == 46: return '.'
        if col == 47: return '-'
        if 48 <= col <= 49: return ':'
        if 50 <= col <= 51: return '='
        if col == 52: return '.'
        if col == 54: return '-'
        if 55 <= col <= 56: return '*'
        if col == 57: return '+'
        if col == 58: return ':'
        if col == 66: return '.'
        if col == 67: return '='
        if 68 <= col <= 82: return '-'
        if col == 83: return '='
        if col == 84: return ':'
        return ' '

    elif row == 17:
        if col == 17: return '.'
        if col == 18: return '='
        if 19 <= col <= 20: return '-'
        if 21 <= col <= 22: return '='
        if 23 <= col <= 24: return ':'
        if col == 25: return '.'
        if col == 30: return '.'
        if 31 <= col <= 32: return ':'
        if 33 <= col <= 34: return '.'
        if col == 39: return '.'
        if col == 40: return ':'
        if 41 <= col <= 44: return '.'
        if 45 <= col <= 46: return '-'
        if 47 <= col <= 48: return ':'
        if col == 49: return '-'
        if col == 50: return '='
        if col == 51: return '+'
        if col == 52: return ':'
        if 55 <= col <= 56: return ':'
        if col == 57: return '.'
        if col == 65: return '.'
        if col == 66: return '-'
        if 67 <= col <= 68: return '.'
        if col == 69: return ':'
        if 70 <= col <= 83: return '-'
        if col == 84: return '='
        if col == 85: return ':'
        return ' '

    elif row == 18:
        if col == 16: return '.'
        if 17 <= col <= 19: return '-'
        if col == 20: return '='
        if col == 21: return '.'
        if col == 24: return '.'
        if 25 <= col <= 27: return ':'
        if 28 <= col <= 29: return '.'
        if col == 33: return '.'
        if 34 <= col <= 35: return ':'
        if col == 36: return '.'
        if 41 <= col <= 42: return '.'
        if col == 43: return ':'
        if col == 44: return '+'
        if col == 45: return '-'
        if col == 46: return '.'
        if col == 48: return '.'
        if col == 49: return '-'
        if 50 <= col <= 51: return '='
        if col == 52: return '+'
        if col == 53: return ':'
        if col == 64: return '.'
        if col == 65: return ':'
        if col == 66: return '.'
        if col == 71: return '.'
        if col == 72: return ':'
        if col == 73: return '='
        if 74 <= col <= 83: return '-'
        if 84 <= col <= 85: return '='
        if col == 86: return ':'
        return ' '

    elif row == 19:
        if 16 <= col <= 19: return '-'
        if col == 20: return '.'
        if col == 27: return '.'
        if 28 <= col <= 30: return ':'
        if 31 <= col <= 32: return '.'
        if col == 36: return '.'
        if col == 43: return ':'
        if col == 44: return '+'
        if 45 <= col <= 46: return '='
        if 47 <= col <= 48: return '-'
        if col == 49: return '='
        if 50 <= col <= 52: return '+'
        if col == 53: return '='
        if 54 <= col <= 55: return ':'
        if 56 <= col <= 61: return '.'
        if 62 <= col <= 63: return ':'
        if col == 64: return '.'
        if col == 73: return '.'
        if col == 74: return '-'
        if col == 75: return '='
        if 76 <= col <= 82: return '-'
        if 83 <= col <= 86: return '='
        if col == 87: return '.'
        return ' '

    elif row == 20:
        if 14 <= col <= 15: return '.'
        if col == 16: return '='
        if col == 17: return '-'
        if col == 18: return '='
        if 19 <= col <= 24: return '.'
        if col == 31: return '.'
        if 32 <= col <= 33: return ':'
        if col == 34: return '.'
        if col == 44: return '='
        if 45 <= col <= 50: return '+'
        if col == 51: return '*'
        if col == 52: return '+'
        if col == 53: return ':'
        if 54 <= col <= 62: return '.'
        if col == 75: return '.'
        if 76 <= col <= 81: return '-'
        if 82 <= col <= 85: return '='
        if col == 86: return '+'
        if col == 87: return '='
        return ' '

    elif row == 21:
        if col == 14: return '.'
        if col == 15: return '-'
        if 16 <= col <= 17: return '='
        if 18 <= col <= 19: return ':'
        if col == 20: return '-'
        if 21 <= col <= 26: return ':'
        if 27 <= col <= 30: return '.'
        if col == 34: return '.'
        if col == 45: return '-'
        if col == 46: return '='
        if 47 <= col <= 49: return '+'
        if 50 <= col <= 51: return '='
        if col == 52: return ':'
        if col == 53: return '.'
        if 62 <= col <= 64: return '.'
        if 65 <= col <= 73: return ':'
        if 74 <= col <= 76: return '.'
        if col == 77: return '-'
        if col == 78: return '='
        if 79 <= col <= 81: return '-'
        if 82 <= col <= 86: return '='
        if col == 87: return '+'
        if col == 88: return ':'
        return ' '

    elif row == 22:
        if col == 15: return '-'
        if col == 16: return '='
        if col == 17: return ':'
        if col == 18: return '.'
        if col == 19: return '-'
        if col == 20: return '.'
        if 27 <= col <= 33: return '.'
        if 46 <= col <= 49: return ':'
        if 50 <= col <= 52: return '.'
        if 59 <= col <= 66: return '.'
        if col == 77: return '.'
        if col == 78: return '-'
        if col == 79: return '='
        if 80 <= col <= 81: return '-'
        if 82 <= col <= 86: return '='
        if col == 87: return '+'
        if col == 88: return '-'
        return ' '

    elif row == 23:
        if col == 15: return '-'
        if col == 16: return '='
        if 17 <= col <= 18: return '.'
        if col == 19: return '-'
        if col == 45: return '.'
        if col == 46: return ':'
        if col == 78: return '.'
        if col == 79: return '-'
        if 80 <= col <= 88: return '='
        return ' '

    elif row == 24:
        if col == 14: return '.'
        if 15 <= col <= 16: return '='
        if col == 18: return '.'
        if col == 19: return '-'
        if col == 20: return ':'
        if col == 21: return '.'
        if col == 45: return ':'
        if col == 46: return '.'
        if 59 <= col <= 61: return '.'
        if 62 <= col <= 68: return ':'
        if 69 <= col <= 72: return '.'
        if 78 <= col <= 79: return '.'
        if 80 <= col <= 88: return '='
        if col == 89: return '.'
        return ' '

    elif row == 25:
        if col == 14: return '.'
        if col == 15: return '='
        if col == 16: return '-'
        if col == 20: return ':'
        if 21 <= col <= 22: return '-'
        if 23 <= col <= 24: return ':'
        if 25 <= col <= 35: return '.'
        if col == 44: return '.'
        if col == 45: return '-'
        if col == 59: return '.'
        if 66 <= col <= 72: return '.'
        if 73 <= col <= 76: return ':'
        if 77 <= col <= 79: return '.'
        if col == 80: return '-'
        if col == 81: return '+'
        if 82 <= col <= 87: return '='
        if col == 88: return '+'
        if col == 89: return '.'
        return ' '

    elif row == 26:
        if 15 <= col <= 16: return '-'
        if col == 21: return '.'
        if col == 22: return ':'
        if col == 23: return '-'
        if col == 24: return '*'
        if 25 <= col <= 37: return '+'
        if 38 <= col <= 41: return '='
        if 42 <= col <= 43: return '-'
        if 44 <= col <= 45: return '='
        if col == 46: return ':'
        if 47 <= col <= 49: return '.'
        if col == 59: return '.'
        if 60 <= col <= 62: return ':'
        if 63 <= col <= 64: return '.'
        if 75 <= col <= 79: return '.'
        if col == 80: return ':'
        if col == 81: return '='
        if col == 82: return '+'
        if 83 <= col <= 87: return '='
        if col == 88: return '+'
        if col == 89: return '.'
        return ' '

    elif row == 27:
        if 8 <= col <= 12: return '.'
        if col == 15: return '-'
        if col == 16: return '='
        if col == 23: return '.'
        if col == 24: return '+'
        if col == 25: return '*'
        if col == 26: return '+'
        if 27 <= col <= 40: return '*'
        if col == 41: return '+'
        if 42 <= col <= 47: return '*'
        if 48 <= col <= 49: return '+'
        if col == 50: return '='
        if col == 51: return '-'
        if 52 <= col <= 53: return ':'
        if 54 <= col <= 55: return '.'
        if 61 <= col <= 62: return '.'
        if 63 <= col <= 66: return ':'
        if 67 <= col <= 68: return '.'
        if 74 <= col <= 79: return '.'
        if col == 80: return ':'
        if col == 81: return '+'
        if 82 <= col <= 83: return '='
        if col == 84: return '+'
        if 85 <= col <= 88: return '='
        if col == 89: return '.'
        return ' '

    elif row == 28:
        if 5 <= col <= 6: return '.'
        if col == 7: return ':'
        if 8 <= col <= 11: return '.'
        if 12 <= col <= 14: return ':'
        if col == 15: return '.'
        if col == 16: return '='
        if col == 17: return '.'
        if col == 24: return ':'
        if col == 25: return '*'
        if 26 <= col <= 27: return '+'
        if col == 28: return '*'
        if 29 <= col <= 43: return '+'
        if col == 44: return '*'
        if 45 <= col <= 47: return '+'
        if 48 <= col <= 52: return '*'
        if 53 <= col <= 54: return '+'
        if 55 <= col <= 56: return '='
        if col == 57: return '-'
        if col == 58: return ':'
        if 59 <= col <= 62: return '.'
        if 64 <= col <= 66: return '.'
        if 67 <= col <= 70: return ':'
        if 71 <= col <= 74: return '.'
        if col == 75: return '-'
        if 76 <= col <= 79: return '.'
        if col == 80: return ':'
        if 81 <= col <= 82: return '='
        if 83 <= col <= 85: return '+'
        if col == 86: return '='
        if col == 87: return '+'
        if col == 88: return '-'
        return ' '

    elif row == 29:
        if col == 4: return '.'
        if col == 5: return ':'
        if col == 6: return '.'
        if col == 13: return '.'
        if col == 14: return ':'
        if col == 15: return '-'
        if col == 16: return '='
        if col == 17: return ':'
        if col == 25: return '='
        if 26 <= col <= 53: return '+'
        if 54 <= col <= 59: return '*'
        if col == 60: return '+'
        if col == 61: return '='
        if 62 <= col <= 63: return '-'
        if col == 64: return ':'
        if 65 <= col <= 69: return '.'
        if 70 <= col <= 71: return ':'
        if 72 <= col <= 73: return '-'
        if col == 74: return '='
        if col == 75: return '-'
        if 76 <= col <= 78: return '.'
        if 79 <= col <= 80: return ':'
        if 81 <= col <= 84: return '+'
        if 85 <= col <= 86: return '='
        if col == 87: return '+'
        if col == 88: return ':'
        return ' '

    elif row == 30:
        if col == 3: return '.'
        if col == 4: return ':'
        if col == 5: return '.'
        if 12 <= col <= 14: return '.'
        if col == 15: return ':'
        if 16 <= col <= 17: return '='
        if col == 18: return '.'
        if col == 25: return '.'
        if 26 <= col <= 40: return '+'
        if 41 <= col <= 42: return '='
        if 43 <= col <= 56: return '+'
        if 57 <= col <= 64: return '*'
        if 65 <= col <= 70: return '+'
        if col == 71: return '='
        if 72 <= col <= 74: return '-'
        if col == 75: return ':'
        if 76 <= col <= 78: return '.'
        if col == 79: return ':'
        if col == 80: return '-'
        if 81 <= col <= 84: return '+'
        if col == 85: return '='
        if col == 86: return '+'
        if col == 87: return '='
        if col == 88: return '.'
        return ' '

    elif row == 31:
        if col == 3: return '.'
        if col == 4: return ':'
        if 11 <= col <= 13: return '.'
        if 14 <= col <= 15: return ':'
        if col == 16: return '='
        if 17 <= col <= 18: return '-'
        if col == 26: return ':'
        if 27 <= col <= 35: return '+'
        if col == 36: return '='
        if 37 <= col <= 45: return '-'
        if 46 <= col <= 47: return '='
        if 48 <= col <= 50: return '+'
        if col == 51: return '='
        if 52 <= col <= 56: return '+'
        if 57 <= col <= 68: return '*'
        if col == 69: return '#'
        if col == 70: return '*'
        if col == 71: return ':'
        if 72 <= col <= 78: return '.'
        if col == 79: return ':'
        if col == 80: return '='
        if 81 <= col <= 84: return '+'
        if col == 85: return '='
        if col == 86: return '+'
        if col == 87: return ':'
        return ' '

    elif row == 32:
        if col == 3: return '.'
        if col == 4: return '-'
        if 5 <= col <= 12: return '.'
        if 13 <= col <= 14: return ':'
        if col == 15: return '-'
        if col == 16: return '+'
        if col == 17: return ':'
        if col == 18: return '-'
        if col == 19: return ':'
        if col == 20: return '.'
        if col == 27: return ':'
        if 28 <= col <= 32: return '+'
        if col == 33: return '='
        if col == 34: return '-'
        if 35 <= col <= 41: return ':'
        if 42 <= col <= 55: return '-'
        if 56 <= col <= 58: return '='
        if col == 59: return '+'
        if col == 60: return '*'
        if 61 <= col <= 63: return '+'
        if 64 <= col <= 68: return '*'
        if col == 69: return '+'
        if col == 70: return ':'
        if 71 <= col <= 77: return '.'
        if col == 78: return ':'
        if col == 79: return '-'
        if 80 <= col <= 83: return '+'
        if col == 84: return '='
        if col == 85: return '+'
        if col == 86: return '='
        if col == 87: return '.'
        return ' '

    elif row == 33:
        if col == 4: return ':'
        if col == 5: return '-'
        if 6 <= col <= 10: return '.'
        if 11 <= col <= 12: return ':'
        if col == 13: return '-'
        if col == 14: return '='
        if 15 <= col <= 17: return '+'
        if 18 <= col <= 19: return '='
        if col == 20: return ':'
        if 21 <= col <= 22: return '.'
        if col == 28: return ':'
        if 29 <= col <= 31: return '+'
        if col == 32: return '='
        if 33 <= col <= 35: return ':'
        if 36 <= col <= 42: return '.'
        if 43 <= col <= 48: return ':'
        if col == 49: return '-'
        if 50 <= col <= 51: return ':'
        if 52 <= col <= 59: return '-'
        if col == 60: return '='
        if col == 61: return '+'
        if col == 62: return '*'
        if 63 <= col <= 67: return '+'
        if col == 68: return '='
        if 69 <= col <= 77: return '.'
        if col == 78: return ':'
        if col == 79: return '='
        if 80 <= col <= 82: return '+'
        if 83 <= col <= 84: return '='
        if col == 85: return '+'
        if col == 86: return '.'
        return ' '

    elif row == 34:
        if col == 5: return ':'
        if 6 <= col <= 11: return '-'
        if col == 12: return '='
        if 13 <= col <= 14: return '+'
        if col == 15: return '='
        if col == 16: return '-'
        if 17 <= col <= 18: return '='
        if 19 <= col <= 20: return '+'
        if col == 21: return ':'
        if 22 <= col <= 23: return '.'
        if col == 29: return '.'
        if col == 30: return '='
        if col == 31: return '+'
        if col == 32: return '-'
        if col == 33: return ':'
        if 34 <= col <= 47: return '.'
        if 48 <= col <= 54: return ':'
        if 55 <= col <= 61: return '-'
        if col == 62: return '+'
        if col == 63: return '*'
        if 64 <= col <= 66: return '+'
        if col == 67: return ':'
        if 68 <= col <= 76: return '.'
        if col == 77: return ':'
        if col == 78: return '='
        if 79 <= col <= 81: return '+'
        if 82 <= col <= 83: return '='
        if col == 84: return '+'
        if col == 85: return ':'
        return ' '

    elif row == 35:
        if col == 7: return '.'
        if col == 8: return ':'
        if col == 9: return '='
        if col == 10: return '*'
        if 11 <= col <= 13: return '+'
        if 14 <= col <= 15: return '='
        if 16 <= col <= 19: return '-'
        if col == 20: return '='
        if col == 21: return '+'
        if col == 22: return '-'
        if 23 <= col <= 25: return '.'
        if col == 31: return ':'
        if 32 <= col <= 33: return '-'
        if col == 34: return ':'
        if 35 <= col <= 52: return '.'
        if 53 <= col <= 58: return ':'
        if 59 <= col <= 61: return '-'
        if col == 62: return '+'
        if col == 63: return '*'
        if col == 64: return '+'
        if col == 65: return '-'
        if 66 <= col <= 72: return '.'
        if 73 <= col <= 76: return ':'
        if col == 77: return '-'
        if 78 <= col <= 83: return '+'
        if col == 84: return ':'
        return ' '

    elif row == 36:
        if col == 9: return '.'
        if 10 <= col <= 11: return '+'
        if 12 <= col <= 14: return '='
        if 15 <= col <= 20: return '-'
        if col == 21: return '='
        if col == 22: return '+'
        if col == 23: return '='
        if 24 <= col <= 27: return '.'
        if col == 33: return '.'
        if col == 34: return ':'
        if col == 35: return '-'
        if 36 <= col <= 37: return ':'
        if 38 <= col <= 52: return '.'
        if 53 <= col <= 57: return ':'
        if 58 <= col <= 59: return '-'
        if 60 <= col <= 62: return '='
        if col == 63: return '-'
        if 64 <= col <= 72: return '.'
        if 73 <= col <= 75: return ':'
        if col == 76: return '='
        if 77 <= col <= 81: return '+'
        if col == 82: return '='
        if col == 83: return ':'
        return ' '

    elif row == 37:
        if col == 10: return ':'
        if col == 11: return '+'
        if 12 <= col <= 14: return '='
        if 15 <= col <= 21: return '-'
        if 22 <= col <= 23: return '='
        if col == 24: return '+'
        if col == 25: return '-'
        if col == 26: return ':'
        if 27 <= col <= 29: return '.'
        if col == 35: return '.'
        if 36 <= col <= 37: return ':'
        if col == 38: return '-'
        if 39 <= col <= 44: return ':'
        if 45 <= col <= 48: return '.'
        if 49 <= col <= 54: return ':'
        if 55 <= col <= 57: return '-'
        if 58 <= col <= 59: return '='
        if col == 60: return '-'
        if col == 61: return ':'
        if 62 <= col <= 70: return '.'
        if 71 <= col <= 74: return ':'
        if col == 75: return '='
        if 76 <= col <= 80: return '+'
        if col == 81: return '-'
        if col == 82: return '.'
        return ' '

    elif row == 38:
        if col == 11: return '.'
        if col == 12: return '='
        if col == 13: return '+'
        if 14 <= col <= 15: return '='
        if 16 <= col <= 21: return '-'
        if 22 <= col <= 23: return '='
        if col == 24: return '+'
        if 25 <= col <= 26: return '='
        if col == 27: return '-'
        if 28 <= col <= 29: return ':'
        if col == 30: return '.'
        if 38 <= col <= 39: return '.'
        if 40 <= col <= 41: return ':'
        if 42 <= col <= 56: return '-'
        if col == 57: return ':'
        if 58 <= col <= 67: return '.'
        if 68 <= col <= 72: return ':'
        if col == 73: return '-'
        if 74 <= col <= 78: return '+'
        if col == 79: return '='
        if col == 80: return ':'
        if col == 81: return '.'
        return ' '

    elif row == 39:
        if col == 12: return '.'
        if col == 13: return '='
        if col == 14: return '+'
        if 15 <= col <= 17: return '='
        if 18 <= col <= 20: return '-'
        if 21 <= col <= 23: return '='
        if 24 <= col <= 25: return '+'
        if 26 <= col <= 29: return '='
        if 30 <= col <= 31: return '-'
        if 32 <= col <= 33: return ':'
        if 34 <= col <= 37: return '.'
        if 40 <= col <= 46: return '.'
        if 47 <= col <= 50: return ':'
        if 51 <= col <= 65: return '.'
        if 66 <= col <= 67: return ':'
        if 68 <= col <= 69: return '.'
        if col == 70: return ':'
        if col == 71: return '-'
        if 72 <= col <= 76: return '+'
        if col == 77: return '='
        if col == 78: return ':'
        if col == 79: return '.'
        return ' '

    elif row == 40:
        if col == 13: return '.'
        if col == 14: return '='
        if col == 15: return '+'
        if 16 <= col <= 18: return '='
        if col == 19: return '-'
        if 20 <= col <= 23: return '='
        if col == 24: return '+'
        if col == 25: return '*'
        if 26 <= col <= 27: return '+'
        if 28 <= col <= 30: return '='
        if 31 <= col <= 32: return '-'
        if 33 <= col <= 35: return '='
        if 36 <= col <= 37: return '-'
        if 38 <= col <= 40: return ':'
        if 41 <= col <= 62: return '.'
        if 63 <= col <= 68: return ':'
        if col == 69: return '='
        if 70 <= col <= 74: return '+'
        if col == 75: return '='
        if col == 76: return ':'
        if col == 77: return '.'
        if 79 <= col <= 80: return '.'
        return ' '

    elif row == 41:
        if col == 14: return '.'
        if col == 15: return '-'
        if 16 <= col <= 17: return '+'
        if 18 <= col <= 22: return '='
        if 23 <= col <= 24: return '+'
        if 25 <= col <= 27: return '='
        if 28 <= col <= 31: return '+'
        if 32 <= col <= 36: return '='
        if 37 <= col <= 38: return '+'
        if 39 <= col <= 44: return '='
        if 45 <= col <= 53: return '-'
        if 54 <= col <= 61: return ':'
        if 62 <= col <= 65: return '-'
        if col == 66: return '='
        if col == 67: return '+'
        if 68 <= col <= 69: return '*'
        if 70 <= col <= 72: return '+'
        if col == 73: return '*'
        if col == 74: return ':'
        if 75 <= col <= 78: return '.'
        return ' '

    elif row == 42:
        if col == 16: return ':'
        if 17 <= col <= 19: return '+'
        if 20 <= col <= 21: return '='
        if 22 <= col <= 23: return '+'
        if col == 24: return '='
        if 25 <= col <= 28: return '-'
        if col == 29: return '='
        if 30 <= col <= 31: return '-'
        if 32 <= col <= 33: return '='
        if 34 <= col <= 36: return '+'
        if col == 37: return '='
        if col == 38: return '-'
        if 39 <= col <= 41: return ':'
        if col == 42: return '-'
        if col == 43: return '='
        if 44 <= col <= 45: return '+'
        if 46 <= col <= 63: return '='
        if 64 <= col <= 71: return '+'
        if col == 72: return '*'
        if col == 73: return '+'
        if col == 74: return ':'
        if col == 75: return '.'
        return ' '

    elif row == 43:
        if col == 17: return '.'
        if col == 18: return '-'
        if 19 <= col <= 22: return '+'
        if col == 23: return '='
        if 24 <= col <= 27: return '-'
        if col == 28: return ':'
        if col == 29: return '.'
        if col == 33: return '.'
        if col == 34: return '-'
        if col == 35: return '='
        if 36 <= col <= 40: return ':'
        if 41 <= col <= 42: return '-'
        if 43 <= col <= 44: return '='
        if 45 <= col <= 46: return '*'
        if 47 <= col <= 55: return '+'
        if 56 <= col <= 57: return '='
        if 58 <= col <= 66: return '+'
        if 67 <= col <= 70: return '*'
        if 71 <= col <= 74: return '+'
        if col == 75: return '='
        if col == 76: return '-'
        if col == 77: return '.'
        return ' '

    elif row == 44:
        if col == 18: return '.'
        if col == 19: return ':'
        if col == 20: return '='
        if col == 21: return '+'
        if col == 22: return '='
        if 23 <= col <= 24: return '-'
        if col == 25: return '='
        if col == 26: return ':'
        if col == 27: return '.'
        if 34 <= col <= 35: return ':'
        if col == 37: return '.'
        if col == 38: return '='
        if col == 39: return '-'
        if 40 <= col <= 41: return '.'
        if col == 42: return '-'
        if col == 43: return '='
        if 44 <= col <= 46: return '+'
        if 47 <= col <= 53: return '-'
        if 54 <= col <= 55: return '='
        if 56 <= col <= 69: return '+'
        if 70 <= col <= 77: return '='
        if col == 78: return '-'
        if col == 79: return ':'
        if col == 80: return '.'
        return ' '

    elif row == 45:
        if col == 19: return '.'
        if col == 20: return ':'
        if col == 21: return '+'
        if 22 <= col <= 23: return '-'
        if col == 24: return '='
        if col == 25: return ':'
        if col == 34: return '.'
        if col == 35: return '-'
        if 36 <= col <= 37: return ':'
        if col == 38: return '+'
        if col == 39: return '='
        if 40 <= col <= 42: return ':'
        if col == 43: return '-'
        if col == 44: return '='
        if col == 45: return '+'
        if col == 46: return '-'
        if 47 <= col <= 48: return '.'
        if 53 <= col <= 55: return '.'
        if col == 56: return ':'
        if 57 <= col <= 58: return '='
        if 59 <= col <= 60: return '-'
        if 61 <= col <= 63: return '='
        if 64 <= col <= 65: return '+'
        if 66 <= col <= 70: return '='
        if 71 <= col <= 76: return '-'
        if 77 <= col <= 80: return '='
        if col == 81: return ':'
        if col == 82: return '.'
        return ' '

    elif row == 46:
        if col == 19: return '.'
        if col == 20: return '-'
        if col == 21: return '='
        if col == 22: return '-'
        if col == 23: return '='
        if col == 24: return ':'
        if col == 35: return '.'
        if 36 <= col <= 37: return '-'
        if col == 38: return '+'
        if 39 <= col <= 41: return '-'
        if 42 <= col <= 44: return '='
        if col == 45: return ':'
        if 46 <= col <= 47: return '.'
        if 55 <= col <= 56: return '.'
        if col == 57: return ':'
        if 58 <= col <= 59: return '='
        if 60 <= col <= 61: return '-'
        if 62 <= col <= 68: return '='
        if 69 <= col <= 79: return '-'
        if 80 <= col <= 81: return '='
        if col == 82: return '-'
        if col == 83: return '.'
        return ' '

    elif row == 47:
        if col == 19: return '.'
        if 20 <= col <= 21: return '='
        if 22 <= col <= 23: return '-'
        if col == 37: return '.'
        if col == 38: return ':'
        if 39 <= col <= 42: return '-'
        if col == 43: return ':'
        if 44 <= col <= 45: return '.'
        if 55 <= col <= 57: return '.'
        if col == 58: return ':'
        if 59 <= col <= 60: return '='
        if col == 61: return '-'
        if 62 <= col <= 70: return '='
        if 71 <= col <= 81: return '-'
        if 82 <= col <= 83: return '='
        if col == 84: return ':'
        if col == 85: return '.'
        return ' '

    elif row == 48:
        if col == 19: return ':'
        if col == 20: return '='
        if col == 21: return '-'
        if col == 22: return '='
        if col == 23: return ':'
        if col == 26: return '.'
        if col == 27: return ':'
        if 28 <= col <= 31: return '.'
        if 56 <= col <= 58: return '.'
        if col == 59: return '-'
        if 60 <= col <= 65: return '='
        if 66 <= col <= 67: return '+'
        if 68 <= col <= 76: return '='
        if 77 <= col <= 80: return '-'
        if 81 <= col <= 84: return '='
        if col == 85: return '-'
        if 86 <= col <= 87: return ':'
        if col == 88: return '.'
        return ' '

    elif row == 49:
        if col == 19: return ':'
        if col == 20: return '='
        if 21 <= col <= 22: return '-'
        if col == 23: return '.'
        if col == 26: return '-'
        if 27 <= col <= 31: return '.'
        if 32 <= col <= 37: return ':'
        if 38 <= col <= 43: return '.'
        if 56 <= col <= 58: return '.'
        if col == 59: return ':'
        if 60 <= col <= 65: return '='
        if col == 66: return '+'
        if 67 <= col <= 68: return '*'
        if 69 <= col <= 72: return '+'
        if 73 <= col <= 81: return '='
        if col == 82: return ':'
        if 83 <= col <= 87: return '.'
        if col == 88: return ':'
        if col == 89: return '-'
        if col == 90: return '.'
        return ' '

    elif row == 50:
        if col == 19: return '-'
        if col == 20: return '='
        if 21 <= col <= 22: return '-'
        if col == 23: return '.'
        if col == 26: return '-'
        if col == 27: return '.'
        if 36 <= col <= 41: return '.'
        if 42 <= col <= 52: return ':'
        if 53 <= col <= 59: return '.'
        if 60 <= col <= 65: return '='
        if 66 <= col <= 67: return '+'
        if 68 <= col <= 70: return '*'
        if 71 <= col <= 75: return '+'
        if 76 <= col <= 79: return '='
        if col == 80: return '-'
        if col == 81: return '.'
        if col == 88: return '.'
        if col == 89: return ':'
        if col == 90: return '-'
        if col == 91: return '.'
        return ' '

    elif row == 51:
        if col == 19: return ':'
        if col == 20: return '='
        if 21 <= col <= 22: return '-'
        if col == 23: return ':'
        if col == 26: return '-'
        if col == 27: return '.'
        if 47 <= col <= 53: return '.'
        if col == 54: return ':'
        if col == 55: return '-'
        if 56 <= col <= 59: return '.'
        if 60 <= col <= 65: return '='
        if 66 <= col <= 69: return '+'
        if col == 70: return '*'
        if col == 71: return '='
        if col == 72: return '.'
        if col == 73: return '-'
        if col == 74: return '='
        if 75 <= col <= 78: return '+'
        if col == 79: return '='
        if col == 80: return '.'
        if 87 <= col <= 89: return '.'
        if col == 90: return ':'
        if col == 91: return '-'
        return ' '

    elif row == 52:
        if col == 19: return ':'
        if col == 20: return '='
        if 21 <= col <= 23: return '-'
        if col == 26: return '.'
        if col == 27: return ':'
        if 47 <= col <= 53: return '.'
        if col == 54: return '='
        if col == 55: return ':'
        if 56 <= col <= 58: return '.'
        if col == 59: return ':'
        if col == 60: return '+'
        if 61 <= col <= 63: return '='
        if 64 <= col <= 70: return '+'
        if col == 71: return '-'
        if col == 75: return '.'
        if col == 76: return ':'
        if col == 77: return '-'
        if col == 78: return '='
        if col == 79: return '-'
        if 80 <= col <= 82: return '.'
        if col == 84: return '.'
        if 86 <= col <= 89: return '.'
        if col == 90: return ':'
        if col == 91: return '-'
        return ' '

    elif row == 53:
        if col == 19: return '.'
        if col == 20: return '='
        if 21 <= col <= 22: return '-'
        if col == 23: return '='
        if col == 24: return ':'
        if 27 <= col <= 28: return ':'
        if 45 <= col <= 52: return '.'
        if 53 <= col <= 54: return '-'
        if 55 <= col <= 58: return '.'
        if 59 <= col <= 63: return '='
        if 64 <= col <= 69: return '+'
        if col == 70: return '*'
        if col == 71: return '-'
        if col == 78: return '.'
        if col == 79: return '-'
        if col == 80: return ':'
        if 81 <= col <= 87: return '.'
        if 88 <= col <= 89: return ':'
        if col == 90: return '-'
        if col == 91: return '.'
        return ' '

    elif row == 54:
        if col == 19: return '.'
        if col == 20: return '='
        if 21 <= col <= 23: return '-'
        if col == 24: return '='
        if col == 25: return '.'
        if 28 <= col <= 29: return ':'
        if col == 30: return '.'
        if 43 <= col <= 51: return '.'
        if 52 <= col <= 53: return '-'
        if 54 <= col <= 57: return '.'
        if col == 58: return '-'
        if 59 <= col <= 63: return '='
        if 64 <= col <= 68: return '+'
        if col == 69: return '='
        if col == 70: return '+'
        if col == 71: return ':'
        if col == 73: return '.'
        if col == 79: return '.'
        if 80 <= col <= 82: return '-'
        if 83 <= col <= 86: return ':'
        if 87 <= col <= 89: return '-'
        if col == 90: return '.'
        return ' '

    elif row == 55:
        if col == 20: return '-'
        if col == 21: return '='
        if 22 <= col <= 24: return '-'
        if col == 25: return '='
        if col == 26: return ':'
        if col == 27: return '.'
        if col == 29: return '.'
        if 30 <= col <= 32: return ':'
        if 33 <= col <= 35: return '.'
        if col == 37: return '.'
        if 39 <= col <= 48: return '.'
        if 49 <= col <= 50: return ':'
        if col == 51: return '-'
        if col == 52: return ':'
        if 53 <= col <= 56: return '.'
        if col == 57: return '-'
        if 58 <= col <= 62: return '='
        if 63 <= col <= 67: return '+'
        if 68 <= col <= 69: return '='
        if col == 70: return '+'
        if col == 71: return '.'
        if col == 81: return '.'
        if col == 82: return ':'
        if 83 <= col <= 86: return '-'
        if col == 87: return ':'
        if 88 <= col <= 89: return '.'
        return ' '

    elif row == 56:
        if col == 20: return '.'
        if col == 21: return '='
        if 22 <= col <= 25: return '-'
        if col == 26: return '='
        if col == 27: return '-'
        if col == 28: return ':'
        if col == 29: return '.'
        if col == 31: return '.'
        if 32 <= col <= 36: return ':'
        if 37 <= col <= 44: return '.'
        if 45 <= col <= 47: return ':'
        if 48 <= col <= 49: return '-'
        if 50 <= col <= 51: return ':'
        if 52 <= col <= 54: return '.'
        if col == 55: return ':'
        if col == 56: return '-'
        if 57 <= col <= 63: return '='
        if 64 <= col <= 66: return '+'
        if 67 <= col <= 68: return '='
        if col == 69: return '+'
        if col == 70: return '-'
        if 71 <= col <= 72: return '.'
        return ' '

    elif row == 57:
        if col == 21: return '-'
        if col == 22: return '='
        if 23 <= col <= 27: return '-'
        if col == 28: return '='
        if col == 29: return '-'
        if col == 30: return ':'
        if 31 <= col <= 35: return '.'
        if 36 <= col <= 40: return ':'
        if 41 <= col <= 45: return '-'
        if 46 <= col <= 48: return ':'
        if 49 <= col <= 51: return '.'
        if 52 <= col <= 53: return ':'
        if col == 54: return '-'
        if 55 <= col <= 62: return '='
        if col == 63: return '+'
        if col == 64: return '='
        if col == 65: return '+'
        if 66 <= col <= 68: return '='
        if col == 69: return '+'
        if col == 70: return ':'
        if 71 <= col <= 72: return '.'
        return ' '

    elif row == 58:
        if col == 21: return ':'
        if col == 22: return '+'
        if 23 <= col <= 28: return '-'
        if 29 <= col <= 32: return '='
        if col == 33: return '-'
        if 34 <= col <= 35: return ':'
        if 36 <= col <= 47: return '.'
        if 48 <= col <= 49: return ':'
        if 50 <= col <= 51: return '-'
        if 52 <= col <= 61: return '='
        if 62 <= col <= 68: return '+'
        if col == 69: return '='
        if 70 <= col <= 71: return '.'
        return ' '

    elif row == 59:
        if col == 21: return '.'
        if col == 22: return '+'
        if 23 <= col <= 28: return '-'
        if 29 <= col <= 41: return '='
        if 42 <= col <= 44: return '-'
        if 45 <= col <= 64: return '='
        if 65 <= col <= 68: return '+'
        if col == 69: return '='
        if 70 <= col <= 73: return '.'
        return ' '

    elif row == 60:
        if col == 21: return '.'
        if col == 22: return '+'
        if 23 <= col <= 28: return '-'
        if 29 <= col <= 33: return '='
        if col == 34: return '+'
        if col == 35: return '='
        if 36 <= col <= 52: return '+'
        if 53 <= col <= 64: return '='
        if col == 65: return '+'
        if col == 66: return '='
        if 67 <= col <= 69: return '+'
        if col == 70: return ':'
        if 71 <= col <= 73: return '.'
        return ' '

    elif row == 61:
        if col == 21: return '.'
        if col == 22: return '='
        if 23 <= col <= 29: return '-'
        if 30 <= col <= 33: return '='
        if 34 <= col <= 35: return '+'
        if 36 <= col <= 38: return '*'
        if 39 <= col <= 52: return '+'
        if 53 <= col <= 64: return '='
        if col == 65: return '+'
        if col == 66: return '='
        if 67 <= col <= 69: return '+'
        if col == 70: return ':'
        if 71 <= col <= 74: return '.'
        return ' '

    elif row == 62:
        if col == 21: return '.'
        if 22 <= col <= 23: return '='
        if 24 <= col <= 29: return '-'
        if 30 <= col <= 34: return '='
        if 35 <= col <= 38: return '+'
        if 39 <= col <= 42: return '*'
        if 43 <= col <= 46: return '='
        if col == 47: return '+'
        if col == 48: return '*'
        if 49 <= col <= 51: return '+'
        if col == 52: return '='
        if col == 53: return '+'
        if 54 <= col <= 63: return '='
        if 64 <= col <= 69: return '+'
        if col == 70: return '-'
        if 71 <= col <= 77: return '.'
        if 81 <= col <= 82: return '.'
        return ' '

    elif row == 63:
        if col == 19: return '.'
        if 20 <= col <= 21: return ':'
        if col == 22: return '-'
        if col == 23: return '+'
        if 24 <= col <= 25: return '='
        if 26 <= col <= 29: return '-'
        if col == 30: return '='
        if col == 31: return '-'
        if 32 <= col <= 35: return '='
        if 36 <= col <= 40: return '+'
        if col == 41: return '*'
        if col == 42: return '+'
        if col == 43: return ':'
        if 44 <= col <= 46: return '.'
        if col == 47: return ':'
        if col == 48: return '='
        if 49 <= col <= 50: return '+'
        if 51 <= col <= 65: return '='
        if 66 <= col <= 67: return '+'
        if col == 68: return '='
        if 69 <= col <= 70: return '+'
        if col == 71: return '-'
        if col == 72: return ':'
        if 73 <= col <= 84: return '.'
        return ' '

    elif row == 64:
        if col == 17: return '.'
        if 18 <= col <= 19: return ':'
        if 20 <= col <= 22: return '.'
        if col == 23: return ':'
        if col == 24: return '-'
        if 25 <= col <= 32: return '='
        if 33 <= col <= 41: return '+'
        if 42 <= col <= 43: return '='
        if 44 <= col <= 48: return ':'
        if 49 <= col <= 50: return '+'
        if 51 <= col <= 65: return '='
        if 66 <= col <= 68: return '+'
        if col == 69: return '='
        if 70 <= col <= 71: return '-'
        if col == 72: return '='
        if col == 73: return '-'
        if 74 <= col <= 88: return '.'
        return ' '

    elif row == 65:
        if col == 16: return '.'
        if col == 17: return '-'
        if col == 18: return '.'
        if 26 <= col <= 27: return '.'
        if 28 <= col <= 29: return ':'
        if 30 <= col <= 32: return '-'
        if 33 <= col <= 34: return '='
        if 35 <= col <= 42: return '-'
        if 43 <= col <= 44: return '='
        if 45 <= col <= 47: return ':'
        if col == 48: return '-'
        if 49 <= col <= 63: return '='
        if 64 <= col <= 65: return '+'
        if 66 <= col <= 67: return '='
        if 68 <= col <= 72: return ':'
        if col == 73: return '='
        if col == 74: return '-'
        if 75 <= col <= 78: return ':'
        if 79 <= col <= 92: return '.'
        return ' '

    elif row == 66:
        if col == 16: return '.'
        if col == 17: return '-'
        if 32 <= col <= 38: return '.'
        if 39 <= col <= 42: return ':'
        if 43 <= col <= 44: return '='
        if 45 <= col <= 47: return '-'
        if 48 <= col <= 49: return '='
        if 50 <= col <= 54: return ':'
        if 55 <= col <= 61: return '-'
        if 62 <= col <= 64: return ':'
        if 65 <= col <= 72: return '.'
        if col == 73: return ':'
        if col == 74: return '='
        if 75 <= col <= 81: return ':'
        if 82 <= col <= 91: return '.'
        return ' '

    elif row == 67:
        if 13 <= col <= 16: return '.'
        if col == 17: return '-'
        if 18 <= col <= 20: return '.'
        if 32 <= col <= 37: return '.'
        if 38 <= col <= 40: return ':'
        if col == 41: return '-'
        if 42 <= col <= 44: return '='
        if col == 45: return '-'
        if 46 <= col <= 49: return '='
        if 50 <= col <= 52: return '.'
        if 68 <= col <= 71: return '.'
        if 72 <= col <= 73: return ':'
        if col == 74: return '='
        if 75 <= col <= 77: return '-'
        if 78 <= col <= 82: return ':'
        if 83 <= col <= 90: return '.'
        return ' '

    elif row == 68:
        if 13 <= col <= 16: return '.'
        if col == 17: return ':'
        if col == 18: return '-'
        if col == 19: return ':'
        if 20 <= col <= 34: return '.'
        if 35 <= col <= 37: return ':'
        if 38 <= col <= 39: return '-'
        if col == 40: return '='
        if col == 41: return '+'
        if 42 <= col <= 45: return '='
        if 46 <= col <= 48: return '-'
        if col == 49: return '='
        if col == 50: return '-'
        if 51 <= col <= 54: return '.'
        if 67 <= col <= 70: return '.'
        if 71 <= col <= 72: return ':'
        if col == 73: return '-'
        if col == 74: return '+'
        if 75 <= col <= 78: return '-'
        if 79 <= col <= 83: return ':'
        if 84 <= col <= 89: return '.'
        return ' '

    elif row == 69:
        if 14 <= col <= 18: return '.'
        if 19 <= col <= 23: return '-'
        if 24 <= col <= 30: return ':'
        if 31 <= col <= 34: return '-'
        if 35 <= col <= 41: return '='
        if 42 <= col <= 49: return '-'
        if col == 50: return '='
        if col == 51: return '-'
        if 52 <= col <= 53: return ':'
        if 54 <= col <= 56: return '.'
        if 64 <= col <= 69: return '.'
        if col == 70: return ':'
        if col == 71: return '-'
        if col == 72: return '='
        if col == 73: return '+'
        if col == 74: return '='
        if 75 <= col <= 77: return '-'
        if 78 <= col <= 81: return ':'
        if 82 <= col <= 88: return '.'
        return ' '

    elif row == 70:
        if 18 <= col <= 21: return '.'
        if 22 <= col <= 25: return ':'
        if 26 <= col <= 34: return '-'
        if 35 <= col <= 51: return ':'
        if 52 <= col <= 55: return '-'
        if 56 <= col <= 57: return ':'
        if 58 <= col <= 65: return '.'
        if 66 <= col <= 67: return ':'
        if 68 <= col <= 69: return '-'
        if 70 <= col <= 72: return '='
        if 73 <= col <= 75: return '-'
        if 76 <= col <= 79: return ':'
        if 80 <= col <= 86: return '.'
        return ' '

    elif row == 71:
        if 25 <= col <= 53: return '.'
        if col == 54: return ':'
        if 55 <= col <= 63: return '-'
        if 64 <= col <= 68: return '='
        if 69 <= col <= 71: return '-'
        if 72 <= col <= 75: return ':'
        if 76 <= col <= 83: return '.'
        return ' '

    elif row == 72:
        if 27 <= col <= 47: return '.'
        if 49 <= col <= 59: return '.'
        if 60 <= col <= 66: return ':'
        if 67 <= col <= 78: return '.'
        return ' '

    elif row == 73:
        if col == 28: return '.'
        if 51 <= col <= 72: return '.'
        return ' '

    elif row == 74:
        if 62 <= col <= 64: return '.'
        return ' '

    elif row == 75:
        return ' '

    elif row == 76:
        return ' '

    elif row == 77:
        return ' '

    elif row == 78:
        return ' '

    elif row == 79:
        return ' '

    elif row == 80:
        return ' '

    elif row == 81:
        return ' '

    return ' '

def render():
    for r in range(82):
        line = ''
        for c in range(100):
            line += get_char(r, c)
        print(line)

if __name__ == '__main__':
    render()
